# Generated by Django 5.2.7 on 2026-09-26 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('root', '0024_businessconfig_targets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('value', models.FloatField(default=0)),
                ('value_type', models.CharField(choices=[('number', 'Number'), ('amount', 'Amount (PKR)')], default='number', max_length=256)),
                ('as_of_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_data_points', to='root.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_manual_data_points', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('data_point_kind', models.CharField(choices=[('base', 'Base'), ('composite', 'Composite')], default='base', max_length=256)),
                ('data_point', models.CharField(max_length=256)),
                ('scope_type', models.CharField(choices=[('business', 'Whole Business'), ('subject', 'One Subject')], default='business', max_length=256)),
                ('subject_type', models.CharField(blank=True, choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('product', 'Product'), ('product_variant', 'Product Variant'), ('employee', 'Employee')], max_length=256, null=True)),
                ('subject_id', models.PositiveIntegerField(blank=True, null=True)),
                ('subject_label', models.CharField(blank=True, max_length=256, null=True)),
                ('period_type', models.CharField(choices=[('month', 'Month'), ('quarter', 'Quarter'), ('year', 'Year'), ('custom', 'Custom Range'), ('rolling', 'Rolling Window')], max_length=256)),
                ('period_year', models.PositiveIntegerField(blank=True, null=True)),
                ('period_month', models.PositiveIntegerField(blank=True, null=True)),
                ('period_quarter', models.PositiveIntegerField(blank=True, null=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('rolling_days', models.PositiveIntegerField(blank=True, null=True)),
                ('target_value', models.FloatField(default=0)),
                ('rule_type', models.CharField(choices=[('threshold', 'Threshold'), ('ratio_to_target', 'Ratio To Target'), ('slab', 'Slab / Ladder'), ('prior_period', 'Prior Period Comparison'), ('elapsed_time', 'Elapsed Time'), ('status_flag', 'Status Flag'), ('combination', 'Combination')], default='threshold', max_length=256)),
                ('outcome', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='root.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_targets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TargetFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('product', 'Product'), ('product_variant', 'Product Variant'), ('entered_by', 'Entered By'), ('invoice_status', 'Invoice Status'), ('payment_method', 'Payment Method'), ('expense_category', 'Expense Category')], max_length=256)),
                ('value_id', models.PositiveIntegerField(blank=True, null=True)),
                ('value_text', models.CharField(blank=True, max_length=256, null=True)),
                ('label', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='targets.target')),
            ],
            options={
                'unique_together': {('target', 'dimension')},
            },
        ),
    ]
