# Generated by Django 5.1.6 on 2025-07-01 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('root', '0008_location_is_default'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('P', 'Planned'), ('IP', 'In Progress'), ('C', 'Completed'), ('X', 'Cancelled')], default='P', max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='root.business')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='root.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='sales.purchaseinvoice')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='purchase_invoices',
            field=models.ManyToManyField(blank=True, through='projects.ProjectPurchaseInvoice', to='sales.purchaseinvoice'),
        ),
        migrations.CreateModel(
            name='ProjectPurchaseQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
