# Generated by Django 5.1.6 on 2025-07-01 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('sales', '0002_purchasequotation_purchasequotationitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpurchasequotation',
            name='purchase_quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='sales.purchasequotation'),
        ),
        migrations.AddField(
            model_name='projectsalesinvoice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectsalesinvoice',
            name='sales_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='sales.salesinvoice'),
        ),
        migrations.AddField(
            model_name='project',
            name='sales_invoices',
            field=models.ManyToManyField(blank=True, through='projects.ProjectSalesInvoice', to='sales.salesinvoice'),
        ),
    ]
