# Generated by Django 5.1.6 on 2025-07-03 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpurchaseinvoice',
            old_name='sales_invoice',
            new_name='purchase_invoice',
        ),
    ]
