# Generated by Django 5.1.6 on 2025-07-03 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_sales_invoice_projectpurchaseinvoice_purchase_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='purchase_invoices',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sales_invoices',
        ),
        migrations.AlterField(
            model_name='projectpurchaseinvoice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='projectpurchasequotation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_quotations', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='projectsalesinvoice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoices', to='projects.project'),
        ),
    ]
