# Generated by Django 5.2.7 on 2026-03-14 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projecttask'),
        ('sales', '0019_purchasequotationitem_supplier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='projectpurchaseinvoice',
            unique_together={('project', 'purchase_invoice')},
        ),
        migrations.AlterUniqueTogether(
            name='projectpurchasequotation',
            unique_together={('project', 'purchase_quotation')},
        ),
        migrations.AlterUniqueTogether(
            name='projectsalesinvoice',
            unique_together={('project', 'sales_invoice')},
        ),
    ]
