# Generated by Django 5.2.7 on 2026-03-16 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_title_project_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='projecttask',
            name='duration',
        ),
    ]
