# Generated by Django 5.2.7 on 2026-03-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_description_project_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
