# Generated by Django 5.2.7 on 2026-03-28 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projecttask_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttask',
            old_name='is_completed',
            new_name='is_complete',
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project'),
        ),
    ]
