# Generated by Django 5.2.7 on 2026-05-18 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userpermconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPermConfig',
        ),
    ]
