"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from dotenv import load_dotenv
from pathlib import Path
from datetime import timedelta


load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n)ih+0wkoxbkcx4#s+ni9@hu9_ojy(rt+f%624^0ulcmi%gf28'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    'localhost', 
    '127.0.0.1',
    '3.110.176.56', 
    'backend.market-pro.pk'
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'rest_framework',
    'django_filters',
    'corsheaders',
    'storages',
    'djoser',
    'core',
    'root',
    'inventory',
    'sales',
    'projects',
    'backlog',
    'accounts',
    'targets',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware'
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
} if DEBUG else {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['RDS_DB_NAME'],
        'USER': os.environ['RDS_DB_USER'],
        'PASSWORD': os.environ['RDS_DB_PASSWORD'],
        'HOST': os.environ['RDS_DB_HOST'],
        'PORT': os.environ['RDS_DB_PORT'],
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Karachi'

USE_I18N = True

USE_TZ = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

SIMPLE_JWT = {
    'AUTH_HEADER_TYPES': ('JWT',),
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=10080),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

DJOSER = {
    'LOGIN_FIELD': 'email',
    'USER_CREATE_PASSWORD_RETYPE': True,
    'PASSWORD_CHANGED_EMAIL_CONFIRMATION': True,
    'SEND_CONFIRMATION_EMAIL': False,
    'PASSWORD_RESET_CONFIRM_RETYPE': True,
    'LOGOUT_ON_PASSWORD_CHANGE': True,
    'PASSWORD_RESET_SHOW_EMAIL_NOT_FOUND': True,
    # The uid and token ride as query params, so the reset screen is a plain
    # route the router does not need a wildcard segment for.
    'PASSWORD_RESET_CONFIRM_URL': 'reset-password?uid={uid}&token={token}',
    'SERIALIZERS': {
        "user": "core.serializers.UserSerializer",
        "current_user": "core.serializers.UserSerializer",
        # Both keys, because djoser chooses between them per request based on
        # USER_CREATE_PASSWORD_RETYPE above -- setting only 'user_create' would
        # silently do nothing while that flag is True.
        "user_create": "core.serializers.UserCreateSerializer",
        "user_create_password_retype":
            "core.serializers.UserCreatePasswordRetypeSerializer",
    },
}

# Where the reset link points. This is the frontend, not the API - the email
# has to land the user on the React screen that collects the new password.
DOMAIN = 'localhost:8080' if DEBUG else 'market-pro.pk'
SITE_NAME = 'Market Pro'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# ── Media storage ─────────────────────────────────────────────────────────────
# Uploads (transaction slips, cheque photos, backlog photos, business logos)
# live on S3 in production and on local disk everywhere else.
#
# Gated on its own flag rather than on DEBUG, for two reasons: DEBUG also
# switches the DATABASE, so you could not point a dev machine at S3 without
# also pointing it at production Postgres; and the switch should be an explicit
# deployment decision, not a side effect.
#
# Why this matters beyond tidiness: uploads currently sit on the instance's own
# disk under MEDIA_ROOT, which is gitignored. Replace or redeploy the box and
# every slip recorded against a transaction is gone, and a missing
# MEDIA_ROOT/transactions/ directory is what made image uploads fail silently
# on the server in the first place.

USE_S3 = os.getenv('USE_S3', 'false').lower() == 'true'

if USE_S3:
    AWS_STORAGE_BUCKET_NAME = os.environ['AWS_STORAGE_BUCKET_NAME']
    AWS_S3_REGION_NAME = os.environ['AWS_S3_REGION_NAME']

    # No access keys here on purpose. boto3 resolves credentials in order and
    # picks up the EC2 instance profile by itself, so the server needs an IAM
    # ROLE rather than a key pair sitting in .env. Setting AWS_ACCESS_KEY_ID /
    # AWS_SECRET_ACCESS_KEY in the environment still works if you must, but a
    # role cannot be leaked by a stray config dump and rotates on its own.

    AWS_S3_SIGNATURE_VERSION = 's3v4'

    # Pin the REGIONAL endpoint. Without it boto3 falls back to the global
    # bucket.s3.amazonaws.com host, which costs a redirect on every object and
    # does not work at all for regions enabled after 2019 - the signature is
    # scoped to the right region either way, so the failure would look like a
    # DNS or SignatureDoesNotMatch error rather than a config mistake.
    AWS_S3_ENDPOINT_URL = os.getenv(
        'AWS_S3_ENDPOINT_URL',
        f'https://s3.{AWS_S3_REGION_NAME}.amazonaws.com',
    )

    # bucket.s3.region.amazonaws.com, not s3.region.amazonaws.com/bucket.
    # Setting an explicit endpoint above makes boto3 default to the path style,
    # which AWS deprecated for buckets created after September 2020.
    AWS_S3_ADDRESSING_STYLE = 'virtual'

    # Bucket owner enforced (ACLs disabled) is the modern default for new
    # buckets, and PutObject fails outright if the client sends an ACL. None
    # means "send no ACL" - do NOT set 'public-read' here.
    AWS_DEFAULT_ACL = None

    # django-storages overwrites a same-named key by default, which would let
    # one upload silently replace another's slip. Django's usual suffixing
    # behaviour is what we want.
    AWS_S3_FILE_OVERWRITE = False

    # These are financial documents - payment slips and cheque images - so the
    # bucket stays private and every URL is presigned and short-lived. The cost
    # is that a URL cannot be cached or shared beyond its expiry, which is the
    # correct trade for this content.
    AWS_QUERYSTRING_AUTH = True
    AWS_QUERYSTRING_EXPIRE = int(os.getenv('AWS_QUERYSTRING_EXPIRE', '3600'))

    # Lets the browser cache an object for the life of its signature.
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': f'private, max-age={AWS_QUERYSTRING_EXPIRE}',
    }

    # Optional: a CloudFront distribution in front of the bucket. Leave unset
    # unless one exists - with AWS_QUERYSTRING_AUTH on, the signature is an S3
    # one, so a plain CloudFront domain will reject it.
    if os.getenv('AWS_S3_CUSTOM_DOMAIN'):
        AWS_S3_CUSTOM_DOMAIN = os.environ['AWS_S3_CUSTOM_DOMAIN']

    MEDIA_LOCATION = os.getenv('AWS_MEDIA_LOCATION', 'media')

# Django 4.2 replaced DEFAULT_FILE_STORAGE/STATICFILES_STORAGE with STORAGES,
# and 5.1 removed the old names. This project is on 5.2, so the dict is the
# only form that works.
STORAGES = {
    'default': {
        'BACKEND': 'storages.backends.s3.S3Storage',
        'OPTIONS': {
            'location': MEDIA_LOCATION,
        },
    } if USE_S3 else {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    # Static files stay on the box: nginx already serves /static/ straight off
    # disk, they are tiny (admin CSS and DRF's browsable API), and putting them
    # on S3 would add a collectstatic upload to every deploy for no gain.
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'core.User'

CORS_ALLOW_ALL_ORIGINS = True

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "mail.spacemail.com"
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = "admin@market-pro.pk"
DEFAULT_FROM_EMAIL = "admin@market-pro.pk"
EMAIL_HOST_PASSWORD = "Polaroids34_"
