# Generated by Django 5.2.7 on 2026-08-01 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('root', '0023_businessconfig_accounting_expense_category'),
        ('sales', '0023_remove_purchaseinvoice_amount_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('cash', 'Cash'), ('wallet', 'Mobile Wallet'), ('bank', 'Bank')], default='cash', max_length=256)),
                ('opening_balance', models.IntegerField(default=0)),
                ('opening_date', models.DateField(auto_now_add=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_accounts', to='root.business')),
            ],
        ),
        migrations.CreateModel(
            name='PartyOpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, help_text='Positive means the customer owes us, or we owe the supplier.')),
                ('as_of_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_opening_balances', to='root.business')),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opening_balance', to='root.customer')),
                ('supplier', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opening_balance', to='root.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sale_payment', 'Sale Payment'), ('customer_receipt', 'Customer Receipt'), ('purchase_return_refund', 'Purchase Return Refund'), ('owner_capital', 'Owner Capital'), ('loan_received', 'Loan Received'), ('other_income', 'Other Income'), ('purchase_payment', 'Purchase Payment'), ('supplier_payment', 'Supplier Payment'), ('sales_return_refund', 'Sales Return Refund'), ('expense', 'Expense'), ('salary_payment', 'Salary Payment'), ('owner_drawings', 'Owner Drawings'), ('loan_repayment', 'Loan Repayment'), ('other_payment', 'Other Payment'), ('transfer', 'Account Transfer'), ('cash_adjustment', 'Cash Adjustment')], max_length=256)),
                ('amount', models.IntegerField(default=0, help_text='Whole rupees. Negative only permitted for cash_adjustment.')),
                ('date', models.DateField(help_text='The date the money moved. Backdating is unrestricted.')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('wallet', 'Wallet'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], default='cash', max_length=256)),
                ('status', models.CharField(choices=[('C', 'CLEARED'), ('PEN', 'PENDING'), ('B', 'BOUNCED')], default='C', max_length=256)),
                ('reference', models.CharField(blank=True, max_length=256, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='transactions')),
                ('cheque_number', models.CharField(blank=True, max_length=256, null=True)),
                ('cheque_due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.moneyaccount')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='root.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_record', to='root.expense')),
                ('purchase_receipt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_record', to='sales.purchasereceipt')),
                ('sales_receipt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_record', to='sales.salesreceipt')),
                ('transfer_account', models.ForeignKey(blank=True, help_text='Destination account when type is transfer.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='accounts.moneyaccount')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_payments', to='root.business')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_payments', to='root.customer')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_payments', to='root.supplier')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='party_payment', to='accounts.transaction')),
            ],
        ),
    ]
