# Generated by Django 5.2.7 on 2026-10-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_moneyaccount_opening_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('sale_payment', 'Sale Payment'), ('customer_receipt', 'Customer Payment'), ('purchase_return_refund', 'Purchase Return Refund'), ('owner_capital', 'Owner Capital'), ('loan_received', 'Loan Received'), ('other_income', 'Other Income'), ('purchase_payment', 'Purchase Payment'), ('supplier_payment', 'Supplier Payment'), ('sales_return_refund', 'Sales Return Refund'), ('expense', 'Expense'), ('salary_payment', 'Salary Payment'), ('owner_drawings', 'Owner Drawings'), ('loan_repayment', 'Loan Repayment'), ('other_payment', 'Other Payment'), ('transfer', 'Account Transfer'), ('cash_adjustment', 'Cash Adjustment')], max_length=256),
        ),
    ]
