# Generated by Django 5.2.7 on 2026-10-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_group',
            field=models.UUIDField(blank=True, db_index=True, help_text='Set when one payment was allocated across several items. Every transaction in a group is one physical payment, so a cheque clears or bounces for the whole group at once.', null=True),
        ),
    ]
