# Generated by Django 5.1.6 on 2025-04-24 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('root', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('track_code', models.CharField(blank=True, max_length=256, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_on_hand', models.IntegerField(blank=True, null=True)),
                ('quantity_reserved', models.IntegerField(blank=True, null=True)),
                ('cost_per_unit', models.FloatField(blank=True, null=True)),
                ('reorder_level', models.IntegerField(blank=True, null=True)),
                ('last_transaction_id', models.IntegerField(blank=True, null=True)),
                ('last_transaction_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.business')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='root.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity_on_hand', models.IntegerField(blank=True, null=True)),
                ('total_value_reserved', models.IntegerField(blank=True, null=True)),
                ('net_inventory_value', models.FloatField(blank=True, null=True)),
                ('last_transaction', models.IntegerField(blank=True, null=True)),
                ('last_transaction_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_glance', to='root.business')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItemHistory',
            fields=[
                ('inventoryitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.inventoryitem')),
                ('version_no', models.IntegerField()),
                ('effective_at', models.DateTimeField(auto_now=True)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.inventoryitem')),
            ],
            options={
                'abstract': False,
            },
            bases=('inventory.inventoryitem',),
        ),
    ]
