# Generated by Django 5.1.6 on 2025-04-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='business_id',
            new_name='business',
        ),
    ]
