# Generated by Django 5.1.6 on 2025-04-29 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_business_id_inventory_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventory'),
            preserve_default=False,
        ),
    ]
