# Generated by Django 5.1.6 on 2025-05-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='cost_per_unit',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='unit_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
