# Generated by Django 5.1.6 on 2025-05-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_inventoryitem_cost_per_unit_and_more'),
        ('root', '0007_product_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('inventory', 'product')},
        ),
    ]
