# Generated by Django 5.1.6 on 2025-05-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventoryitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity_on_hand',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity_reserved',
            field=models.IntegerField(default=0),
        ),
    ]
