# Generated by Django 5.1.6 on 2025-06-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventoryitem_quantity_on_hand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='last_transaction_at',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='last_transaction_at',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='last_transaction_id',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='last_transaction',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='last_transaction',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
