# Generated by Django 5.2.7 on 2026-01-31 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventoryitem_unit_price'),
        ('root', '0014_productvariant_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='product_var',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root.productvariant'),
        ),
    ]
