# Generated by Django 5.2.7 on 2026-02-08 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventoryitem_product_var'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='product_var',
        ),
    ]
