# Generated by Django 5.2.7 on 2026-02-08 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_inventoryitem_product_var'),
        ('root', '0016_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='product_var',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root.productvariant'),
        ),
    ]
