# Generated by Django 5.2.7 on 2026-02-12 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_inventoryitem_product_var'),
        ('root', '0016_productvariant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('inventory', 'product_var')},
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='product',
        ),
    ]
