# Generated by Django 5.2.7 on 2026-02-13 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_inventoryitem_unique_together_and_more'),
        ('root', '0016_productvariant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='product_var',
            new_name='product',
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('inventory', 'product')},
        ),
    ]
