# Generated by Django 5.1.6 on 2025-04-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='abv',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
