# Generated by Django 5.1.6 on 2025-05-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
