# Generated by Django 5.2.7 on 2025-11-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_location_is_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
