# Generated by Django 5.2.7 on 2025-12-28 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_remove_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sales_enabled', models.BooleanField(default=True)),
                ('is_purchases_enabled', models.BooleanField(default=True)),
                ('is_projects_enabled', models.BooleanField(default=False)),
                ('is_inventory_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
