# Generated by Django 5.2.7 on 2026-01-31 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0013_productvarianttype_product_code_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='root.productvariant'),
        ),
    ]
