# Generated by Django 5.2.7 on 2026-02-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_inventoryitem_product_var'),
        ('root', '0014_productvariant_parent'),
        ('sales', '0012_remove_purchaseinvoiceitem_product_var_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='sku_counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
