# Generated by Django 5.2.7 on 2026-02-13 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0016_productvariant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='product',
            new_name='base',
        ),
    ]
