# Generated by Django 5.2.7 on 2026-05-12 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0018_businessconfig_is_quotations_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessconfig',
            name='user',
        ),
        migrations.AddField(
            model_name='businessconfig',
            name='business',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='business_config', to='root.business'),
            preserve_default=False,
        ),
    ]
