# Generated by Django 5.2.7 on 2026-05-16 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0020_alter_employee_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessconfig',
            old_name='is_inventory_enabled',
            new_name='inventory',
        ),
        migrations.RenameField(
            model_name='businessconfig',
            old_name='is_projects_enabled',
            new_name='projects',
        ),
        migrations.RenameField(
            model_name='businessconfig',
            old_name='is_purchases_enabled',
            new_name='purchases',
        ),
        migrations.RenameField(
            model_name='businessconfig',
            old_name='is_quotations_enabled',
            new_name='quotations',
        ),
        migrations.RenameField(
            model_name='businessconfig',
            old_name='is_returned_items_enabled',
            new_name='returned_items',
        ),
        migrations.RenameField(
            model_name='businessconfig',
            old_name='is_sales_enabled',
            new_name='sales',
        ),
        migrations.AlterField(
            model_name='employeeaccess',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='root.employee'),
        ),
    ]
