# Generated by Django 5.2.7 on 2026-05-18 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0021_rename_is_inventory_enabled_businessconfig_inventory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessconfig',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='root.business'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('business', 'user')},
        ),
    ]
