# Generated by Django 5.2.7 on 2026-08-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0022_alter_businessconfig_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessconfig',
            name='accounting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, choices=[('kiraya', 'Rent (Kiraya)'), ('bijli', 'Electricity (Bijli)'), ('tankhwa', 'Salaries (Tankhwa)'), ('transport', 'Transport'), ('mutafarriq', 'Miscellaneous (Mutafarriq)')], max_length=256, null=True),
        ),
    ]
