# Generated by Django 5.2.7 on 2026-09-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0023_businessconfig_accounting_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessconfig',
            name='targets',
            field=models.BooleanField(default=False),
        ),
    ]
