# Generated by Django 5.1.6 on 2025-04-24 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('root', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_due', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('D', 'DRAFT'), ('R', 'RECEIVED'), ('P', 'PAID'), ('C', 'CANCELLED')], default=('R', 'RECEIVED'), max_length=256)),
                ('sub_total', models.FloatField()),
                ('tax', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField()),
                ('delivery', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to='root.business')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_purchase_invoices', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_invoices', to='root.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('track_code', models.CharField(blank=True, max_length=256, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_cost', models.FloatField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.product')),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inovice_items', to='sales.purchaseinvoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=256)),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('date_due', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('D', 'DRAFT'), ('S', 'SENT'), ('P', 'PAID'), ('C', 'CANCELLED')], default=('P', 'PAID'), max_length=256)),
                ('sub_total', models.FloatField()),
                ('tax', models.FloatField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('total', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.business')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sales_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_invoices', to='root.customer')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('track_code', models.CharField(blank=True, max_length=256, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.product')),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='sales.salesinvoice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
