# Generated by Django 5.1.6 on 2025-06-28 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('root', '0008_location_is_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_due', models.DateField(blank=True, null=True)),
                ('tax', models.JSONField(blank=True, default=dict, help_text='e.g., {"value": 10.0, "type": "percentage" or "amount"}', null=True)),
                ('status', models.CharField(choices=[('D', 'DRAFT'), ('R', 'RECEIVED'), ('PR', 'PARTIALLY_RECEIVED'), ('C', 'CANCELLED'), ('O', 'OVERDUE')], default=('R', 'RECEIVED'), max_length=256)),
                ('payment_status', models.CharField(choices=[('P', 'PAID'), ('PP', 'PARTIALLY_PAID'), ('PEN', 'PENDING'), ('RF', 'REFUNDED'), ('C', 'CANCELLED')], default=('PEN', 'PENDING'), max_length=256)),
                ('sub_total', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('amount_paid', models.FloatField(blank=True, null=True)),
                ('goods_received', models.IntegerField(blank=True, null=True)),
                ('delivery', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_restocked', models.BooleanField(default=False)),
                ('is_partially_restocked', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to='root.business')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_purchase_invoices', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_invoices', to='root.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('track_code', models.CharField(blank=True, max_length=256, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_cost', models.FloatField()),
                ('quantity_received', models.IntegerField(blank=True, null=True)),
                ('is_restocked', models.BooleanField(default=False)),
                ('is_partially_restocked', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.product')),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='sales.purchaseinvoice')),
            ],
            options={
                'unique_together': {('purchase_invoice', 'product')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItemRestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('received_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restocks', to='sales.purchaseinvoice')),
                ('purchase_invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restocks', to='sales.purchaseinvoiceitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=256)),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('date_due', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('D', 'DRAFT'), ('S', 'SENT'), ('O', 'OVERDUE'), ('X', 'CANCELLED'), ('C', 'COMPLETED'), ('PC', 'PARTIALLY_COMPLETED')], default=('O', 'OVERDUE'), max_length=256)),
                ('payment_status', models.CharField(choices=[('P', 'PAID'), ('PP', 'PARTIALLY_PAID'), ('PEN', 'PENDING'), ('RF', 'REFUNDED'), ('C', 'CANCELLED')], default=('PEN', 'PENDING'), max_length=256)),
                ('sub_total', models.FloatField(blank=True, null=True)),
                ('tax', models.JSONField(blank=True, default=dict, help_text='e.g., {"value": 10.0, "type": "percentage" or "amount"}', null=True)),
                ('discount', models.JSONField(blank=True, default=dict, help_text='e.g., {"value": 10.0, "type": "percentage" or "amount"}', null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_deducted', models.BooleanField(default=False)),
                ('is_partially_deducted', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.business')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sales_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_invoices', to='root.customer')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('track_code', models.CharField(blank=True, max_length=256, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('discount', models.JSONField(blank=True, default=dict, help_text='e.g., {"value": 10.0, "type": "percentage" or "amount"}', null=True)),
                ('quantity_received', models.IntegerField(blank=True, null=True)),
                ('is_deducted', models.BooleanField(default=False)),
                ('is_partially_deducted', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.product')),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='sales.salesinvoice')),
            ],
            options={
                'unique_together': {('sales_invoice', 'product')},
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceItemDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('received_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restocks', to='sales.salesinvoice')),
                ('sales_invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restocks', to='sales.salesinvoiceitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('received_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='sales.salesinvoice')),
                ('sales_invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='sales.salesinvoiceitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
