# Generated by Django 5.1.6 on 2025-07-01 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_location_is_default'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_no', models.CharField(blank=True, max_length=256, null=True)),
                ('expected_response_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('S', 'Sent'), ('A', 'Accepted'), ('R', 'Rejected'), ('X', 'Cancelled')], default='D', max_length=256)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_quotations', to='root.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseQuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('track_code', models.CharField(blank=True, max_length=256, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.product')),
                ('purchase_quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.purchasequotation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseQuotationSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('purchase_quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.purchasequotation')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='purchasequotation',
            name='suppliers',
            field=models.ManyToManyField(through='sales.PurchaseQuotationSupplier', to='root.supplier'),
        ),
    ]
