# Generated by Django 5.2.7 on 2025-11-01 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_location_is_default'),
        ('sales', '0002_purchasequotation_purchasequotationitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ReturnedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_items', to='root.business')),
                ('invoice_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='returned_item', to='sales.salesinvoiceitem')),
            ],
        ),
    ]
