# Generated by Django 5.1.6 on 2025-04-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_purchaseinvoiceitem_purchase_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='date_due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
