# Generated by Django 5.1.6 on 2025-04-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_purchaseinvoice_date_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='delivery',
            field=models.DateField(blank=True, null=True),
        ),
    ]
