# Generated by Django 5.2.7 on 2025-11-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesinvoiceitem_is_returned_returneditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='returneditem',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
