# Generated by Django 5.1.6 on 2025-04-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_purchaseinvoice_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='date_due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
