# Generated by Django 5.2.7 on 2025-11-14 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_remove_product_image'),
        ('sales', '0004_returneditem_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='is_partially_returned',
            field=models.BooleanField(default=False),
        ),
        # Note: AddConstraint operations below were intentionally deferred
        # migrations.AddConstraint(model_name='purchaseinvoice', ...)
        # migrations.AddConstraint(model_name='purchaseinvoiceitem', ...)
        # migrations.AddConstraint(model_name='salesinvoice', ...)
        # migrations.AddConstraint(model_name='salesinvoiceitem', ...)
    ]
