# Generated by Django 5.2.7 on 2025-12-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salesinvoiceitem_is_partially_returned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
