# Generated by Django 5.1.6 on 2025-05-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_product_is_active'),
        ('sales', '0005_alter_salesinvoice_date_due'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaseinvoiceitem',
            unique_together={('purchase_invoice', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='salesinvoiceitem',
            unique_together={('sales_invoice', 'product')},
        ),
    ]
