# Generated by Django 5.2.7 on 2025-12-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_salesinvoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoiceitemrestock',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='returneditem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitem',
            name='quantity_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitemdeduction',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salesreservation',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
