# Generated by Django 5.2.7 on 2025-12-28 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0010_businessconfig'),
        ('sales', '0007_alter_purchaseinvoiceitemrestock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='quantity_received',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SalesConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_sale_auto_update_inventory', models.BooleanField(default=True)),
                ('on_purchase_auto_update_inventory', models.BooleanField(default=True)),
                ('is_returned_items_enabled', models.BooleanField(default=False)),
                ('business_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_config', to='root.businessconfig')),
            ],
        ),
    ]
