# Generated by Django 5.2.7 on 2026-01-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_purchaseinvoiceitem_quantity_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoiceitemrestock',
            name='received_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitemdeduction',
            name='received_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesreservation',
            name='received_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
