# Generated by Django 5.2.7 on 2026-01-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_purchaseinvoiceitemrestock_received_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchaseinvoice',
            name='is_restocked_and_is_partially_restocked_mutually_exclusive_pi',
        ),
        migrations.RemoveConstraint(
            model_name='purchaseinvoiceitem',
            name='is_restocked_and_is_partially_restocked_mutually_exclusive_pii',
        ),
        migrations.RemoveConstraint(
            model_name='salesinvoice',
            name='is_deducted_and_is_partially_deducted_mutually_exclusive_si',
        ),
        migrations.RemoveConstraint(
            model_name='salesinvoiceitem',
            name='is_returned_and_is_partially_returned_mutually_exclusive',
        ),
        migrations.RemoveConstraint(
            model_name='salesinvoiceitem',
            name='is_deducted_and_is_partially_deducted_mutually_exclusive_sii',
        ),
        migrations.AddField(
            model_name='returneditem',
            name='is_damaged',
            field=models.BooleanField(default=False),
        ),
    ]
