# Generated by Django 5.2.7 on 2026-01-31 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0014_productvariant_parent'),
        ('sales', '0010_remove_purchaseinvoice_is_restocked_and_is_partially_restocked_mutually_exclusive_pi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='product_var',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root.productvariant'),
        ),
        migrations.AddField(
            model_name='purchasequotationitem',
            name='product_var',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root.productvariant'),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='product_var',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root.productvariant'),
        ),
    ]
