# Generated by Django 5.2.7 on 2026-02-08 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_purchaseinvoiceitem_product_var_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoiceitem',
            name='product_var',
        ),
        migrations.RemoveField(
            model_name='purchasequotationitem',
            name='product_var',
        ),
        migrations.RemoveField(
            model_name='salesinvoiceitem',
            name='product_var',
        ),
    ]
