# Generated by Django 5.2.7 on 2026-02-08 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0016_productvariant'),
        ('sales', '0012_remove_purchaseinvoiceitem_product_var_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='product_var',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root.productvariant'),
        ),
        migrations.AddField(
            model_name='purchasequotationitem',
            name='product_var',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root.productvariant'),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='product_var',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root.productvariant'),
        ),
    ]
