# Generated by Django 5.2.7 on 2026-02-12 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0016_productvariant'),
        ('sales', '0013_purchaseinvoiceitem_product_var_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaseinvoiceitem',
            unique_together={('purchase_invoice', 'product_var')},
        ),
        migrations.RemoveField(
            model_name='purchasequotationitem',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='salesinvoiceitem',
            unique_together={('sales_invoice', 'product_var')},
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='salesinvoiceitem',
            name='product',
        ),
    ]
