# Generated by Django 5.2.7 on 2026-02-13 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0016_productvariant'),
        ('sales', '0014_alter_purchaseinvoiceitem_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseinvoiceitem',
            old_name='product_var',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='purchasequotationitem',
            old_name='product_var',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='salesinvoiceitem',
            old_name='product_var',
            new_name='product',
        ),
        migrations.AlterUniqueTogether(
            name='purchaseinvoiceitem',
            unique_together={('purchase_invoice', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='salesinvoiceitem',
            unique_together={('sales_invoice', 'product')},
        ),
    ]
