# Generated by Django 5.2.7 on 2026-02-18 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_rename_product_var_purchaseinvoiceitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returneditem',
            name='return_type',
            field=models.CharField(blank=True, choices=[('to_invoice', 'To Invoice'), ('to_inventory', 'To Inventory')], max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoiceitem',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='returneditem',
            name='invoice_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='sales.salesinvoiceitem'),
        ),
    ]
