# Generated by Django 5.2.7 on 2026-02-19 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_returneditem_return_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoiceitem',
            name='is_partially_returned',
        ),
        migrations.RemoveField(
            model_name='salesinvoiceitem',
            name='is_returned',
        ),
    ]
