# Generated by Django 5.2.7 on 2026-03-01 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0017_rename_product_productvariant_base'),
        ('sales', '0017_remove_salesinvoiceitem_is_partially_returned_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasequotation',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='purchasequotation',
            old_name='date_updated',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='purchasequotation',
            name='expected_response_at',
        ),
        migrations.RemoveField(
            model_name='purchasequotation',
            name='suppliers',
        ),
        migrations.AddField(
            model_name='purchasequotationsupplier',
            name='expected_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasequotationsupplier',
            name='purchase_quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='sales.purchasequotation'),
        ),
        migrations.AlterField(
            model_name='purchasequotationsupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_quotations', to='root.supplier'),
        ),
    ]
