# Generated by Django 5.2.7 on 2026-03-07 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0017_rename_product_productvariant_base'),
        ('sales', '0018_rename_date_created_purchasequotation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasequotationitem',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_items', to='root.supplier'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PurchaseQuotationSupplier',
        ),
    ]
