# Generated by Django 5.2.7 on 2026-03-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_purchasequotationitem_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasequotationitem',
            name='is_fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
