# Generated by Django 5.2.7 on 2026-05-20 19:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_purchasereceipt_salesreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereceipt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasereceipt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='salesreceipt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesreceipt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
