# Generated by Django 5.2.7 on 2026-05-20 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_purchasereceipt_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='amount_paid',
        ),
    ]
