# Generated by Django 5.2.7 on 2026-08-05 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_remove_purchaseinvoice_amount_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='payment_status',
        ),
    ]
