# Generated by Django 5.2.7 on 2026-08-11 22:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_remove_purchaseinvoice_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='date_issued',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
