# Generated by Django 5.2.7 on 2026-08-11 23:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_alter_salesinvoice_date_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoiceitemrestock',
            name='received_at',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoiceitemdeduction',
            name='received_at',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AlterField(
            model_name='salesreservation',
            name='received_at',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
    ]
