# Generated by Django 5.2.7 on 2026-09-26 15:16

import django.utils.timezone
from django.db import migrations, models
from django.db.models import F


def backfill_date_issued(apps, schema_editor):
    """
    AddField stamps every existing row with 'now', which would put every
    historical purchase in the current period. Copy created_at over it so an
    old invoice keeps the day it was entered.

    One UPDATE with an F() expression: no Python loop, and it bypasses
    auto_now, so updated_at is left alone.
    """
    PurchaseInvoice = apps.get_model('sales', 'PurchaseInvoice')
    (PurchaseInvoice.objects
     .using(schema_editor.connection.alias)
     .update(date_issued=F('created_at')))


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_alter_purchaseinvoiceitemrestock_received_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='date_issued',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        # Reversing the AddField drops the column, so there is nothing for the
        # reverse of the backfill to undo.
        migrations.RunPython(backfill_date_issued, migrations.RunPython.noop),
    ]
